# Generated by Django 4.1.5 on 2023-01-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='')),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('admin', 'Admin'), ('sales', 'Sales'), ('production', 'Production'), ('devloper', 'Developer'), ('client', 'Client')], default='client', max_length=10),
        ),
    ]
