# Generated by Django 4.1.5 on 2023-01-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_file_1_alter_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_1',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Is admin'),
        ),
        migrations.AddField(
            model_name='file_1',
            name='is_client',
            field=models.BooleanField(default=False, verbose_name='Is client'),
        ),
        migrations.AddField(
            model_name='file_1',
            name='is_devloper',
            field=models.BooleanField(default=False, verbose_name='Is devloper'),
        ),
        migrations.AddField(
            model_name='file_1',
            name='is_production',
            field=models.BooleanField(default=False, verbose_name='Is production'),
        ),
        migrations.AddField(
            model_name='file_1',
            name='is_sales',
            field=models.BooleanField(default=False, verbose_name='Is sales'),
        ),
    ]
