# Generated by Django 4.1.5 on 2023-01-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_file_1_is_admin_file_1_is_client_file_1_is_devloper_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_1',
            name='is_admin',
            field=models.BooleanField(default=True, verbose_name='Is admin'),
        ),
    ]
