# Generated by Django 4.1.5 on 2023-01-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_file_1_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_1',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='file_1',
            name='is_client',
        ),
        migrations.RemoveField(
            model_name='file_1',
            name='is_devloper',
        ),
        migrations.RemoveField(
            model_name='file_1',
            name='is_production',
        ),
        migrations.RemoveField(
            model_name='file_1',
            name='is_sales',
        ),
        migrations.AddField(
            model_name='file_1',
            name='is_admin_file',
            field=models.BooleanField(default=True, verbose_name='Is admin file'),
        ),
        migrations.AddField(
            model_name='file_1',
            name='is_client_file',
            field=models.BooleanField(default=False, verbose_name='Is client file'),
        ),
        migrations.AddField(
            model_name='file_1',
            name='is_devloper_file',
            field=models.BooleanField(default=False, verbose_name='Is devloper file'),
        ),
        migrations.AddField(
            model_name='file_1',
            name='is_production_file',
            field=models.BooleanField(default=False, verbose_name='Is production file'),
        ),
        migrations.AddField(
            model_name='file_1',
            name='is_sales_file',
            field=models.BooleanField(default=False, verbose_name='Is sales file'),
        ),
    ]
