# Generated by Django 4.1.5 on 2023-01-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_file_1_description_remove_file_1_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_1',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='file_1',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='file_1',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
