# Generated by Django 4.1.5 on 2023-01-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_file_1_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_1',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
