# Generated by Django 4.1.5 on 2023-01-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_employee',
        ),
        migrations.AddField(
            model_name='user',
            name='is_client',
            field=models.BooleanField(default=False, verbose_name='Is client'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_devloper',
            field=models.BooleanField(default=False, verbose_name='Is devloper'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_production',
            field=models.BooleanField(default=False, verbose_name='Is production'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_sales',
            field=models.BooleanField(default=False, verbose_name='Is sales'),
        ),
    ]
