# Generated by Django 4.1.5 on 2023-01-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_is_customer_remove_user_is_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('sales', 'SALES'), ('production', 'PRODUCTION'), ('devloper', 'DEVLOPER'), ('client', 'CLIENT')], default='admin', max_length=10),
        ),
    ]
