# Generated by Django 4.1.5 on 2023-01-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='files')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('is_admin_file', models.BooleanField(default=True, verbose_name='Is admin file')),
                ('is_sales_file', models.BooleanField(default=False, verbose_name='Is sales file')),
                ('is_production_file', models.BooleanField(default=False, verbose_name='Is production file')),
                ('is_devloper_file', models.BooleanField(default=False, verbose_name='Is devloper file')),
                ('is_client_file', models.BooleanField(default=False, verbose_name='Is client file')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('admin', 'Admin'), ('sales', 'Sales'), ('production', 'Production'), ('devloper', 'Developer'), ('client', 'Client')], default='client', max_length=10),
        ),
    ]
