# Generated by Django 4.1.5 on 2023-01-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_file_1_alter_user_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_1',
            name='is_admin_file',
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('sales', 'Sales'), ('production', 'Production'), ('devloper', 'Developer'), ('client', 'Client')], default='client', max_length=10),
        ),
    ]
