# Generated by Django 4.1.5 on 2023-01-27 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_file_1_is_admin_remove_file_1_is_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_1',
            name='description',
        ),
        migrations.RemoveField(
            model_name='file_1',
            name='file',
        ),
        migrations.RemoveField(
            model_name='file_1',
            name='title',
        ),
    ]
