# Generated by Django 4.1.5 on 2023-01-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_file_1_description_file_1_file_file_1_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_1',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='file_1',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='file_1',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
