# Generated by Django 4.1.5 on 2023-01-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_file_1_description_alter_file_1_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_1',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
